const API="https://podcasts-dashboard-api.onrender.com";
let password=sessionStorage.getItem("podcastDashboardPassword")||"";
let data=null;
const $=s=>document.querySelector(s), view=$("#view");
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json","X-Dashboard-Password":password,...(options.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||("HTTP "+r.status));return j}
function badge(v){const c=v==="success"||v==="completed"||v==="uploaded"?"success":v==="failure"||v==="error"?"danger":v==="in_progress"||v==="queued"?"warning":"";return '<span class="badge '+c+'">'+(v||"—")+"</span>"}
function date(v){return v?new Date(v).toLocaleString("he-IL"):"—"}
async function load(){try{data=await api("/api/overview");$("#apiDot").className="dot ok";$("#apiText").textContent="API מחובר";render(current)}catch(e){$("#apiDot").className="dot bad";$("#apiText").textContent="שגיאת API";throw e}}
let current="overview";
function render(name){current=name;document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.view===name));const titles={overview:["סקירה כללית","מצב מערכת הפודקאסטים"],run:["הרצה חדשה","הפעלת הורדה ידנית"],podcasts:["פודקאסטים","הגדרות ומצב מקורות"],episodes:["פרקים","בקרת העלאות Drive ו-Yemos"],runs:["הרצות","היסטוריית GitHub Actions"],errors:["שגיאות","פריטים הדורשים טיפול"]};$("#title").textContent=titles[name][0];$("#subtitle").textContent=titles[name][1];({overview:overview,run:runView,podcasts:podcasts,episodes:episodes,runs:runs,errors:errors}[name])()}
function overview(){const t=data.totals,r=data.runs[0];view.innerHTML='<div class="cards"><div class="card"><div class="label">פודקאסטים פעילים</div><div class="value">'+t.enabled+'</div></div><div class="card"><div class="label">פרקים במעקב</div><div class="value">'+t.episodes+'</div></div><div class="card"><div class="label">Drive</div><div class="value">'+t.drive_uploaded+'</div></div><div class="card"><div class="label">Yemos</div><div class="value">'+t.yemos_uploaded+'</div></div></div><div class="panel"><h2>הרצה אחרונה</h2>'+(r?'<b>#'+r.number+'</b> · '+badge(r.status==="completed"?r.conclusion:r.status)+' · '+date(r.created_at):"אין נתונים")+'</div><div class="panel"><h2>מצב פידים</h2>'+feedTable()+'</div>'}
function feedTable(){return '<div class="table-wrap"><table><thead><tr><th>פודקאסט</th><th>ענף Yemos</th><th>בדיקה אחרונה</th><th>מצב</th></tr></thead><tbody>'+data.podcasts.map(p=>{const f=data.feeds[p.id]||{};return '<tr><td>'+esc(p.name)+'</td><td>'+esc(p.yemos_branch)+'</td><td>'+date(f.last_checked)+'</td><td>'+(f.last_error?badge("error"):badge(p.enabled===false?"disabled":"success"))+'</td></tr>'}).join("")+'</tbody></table></div>'}
function runView(){view.innerHTML='<div class="panel"><div class="toolbar"><label>מצב <select id="mode"><option value="latest">אחרונים</option><option value="all">כל הפרקים ב-RSS</option></select></label><label>מספר אחרונים <input id="count" type="number" min="1" max="1000" value="1"></label><button id="all" class="edit-btn">בחר הכל</button><button id="none" class="edit-btn">נקה</button></div><div class="podcast-grid">'+data.podcasts.filter(p=>p.enabled!==false).map(p=>'<label class="check"><input type="checkbox" value="'+p.id+'"> '+esc(p.name)+'</label>').join("")+'</div><div style="margin-top:18px"><button id="start" class="primary">▶ הפעל הרצה</button> <span id="runMsg"></span></div></div>';$("#all").onclick=()=>document.querySelectorAll('.check input').forEach(x=>x.checked=true);$("#none").onclick=()=>document.querySelectorAll('.check input').forEach(x=>x.checked=false);$("#mode").onchange=()=>$("#count").disabled=$("#mode").value==="all";$("#start").onclick=async()=>{const ids=[...document.querySelectorAll('.check input:checked')].map(x=>x.value);if(!ids.length&&!confirm("לא נבחרו פודקאסטים. להפעיל על כל הפודקאסטים הפעילים?"))return;$("#start").disabled=true;$("#runMsg").textContent="שולח…";try{await api("/api/run",{method:"POST",body:JSON.stringify({mode:$("#mode").value,count:+$("#count").value||1,podcasts:ids})});$("#runMsg").textContent="✓ ההרצה נשלחה ל-GitHub Actions";setTimeout(async()=>{await load();render("runs")},2500)}catch(e){$("#runMsg").textContent="שגיאה: "+e.message}finally{$("#start").disabled=false}}}
function podcasts(){view.innerHTML='<div class="panel">'+feedTable()+'</div><div class="panel"><h2>עריכה</h2><p>בחר פודקאסט לעריכת שם, RSS, תיקיית Drive, ענף Yemos או מצב פעיל.</p><select id="editPodcast">'+data.podcasts.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("")+'</select> <button class="primary" id="edit">ערוך</button><div id="editor"></div></div>';$("#edit").onclick=()=>editPodcast($("#editPodcast").value)}
function editPodcast(id){const p=data.podcasts.find(x=>x.id===id);$("#editor").innerHTML='<div class="toolbar" style="margin-top:15px"><input id="eName" value="'+attr(p.name)+'" placeholder="שם"><input id="eRss" value="'+attr(p.rss)+'" placeholder="RSS" style="min-width:300px"><input id="eDrive" value="'+attr(p.drive_folder||"")+'" placeholder="Drive"><input id="eBranch" value="'+attr(p.yemos_branch)+'" placeholder="Yemos"><label><input id="eEnabled" type="checkbox" '+(p.enabled!==false?"checked":"")+'> פעיל</label><button id="save" class="primary">שמור</button><span id="saveMsg"></span></div>';$("#save").onclick=async()=>{try{await api("/api/podcasts/"+id,{method:"PUT",body:JSON.stringify({name:$("#eName").value,rss:$("#eRss").value,drive_folder:$("#eDrive").value,yemos_branch:$("#eBranch").value,enabled:$("#eEnabled").checked})});$("#saveMsg").textContent="✓ נשמר. GitHub Actions יראה את השינוי בהרצה הבאה.";await load()}catch(e){$("#saveMsg").textContent="שגיאה: "+e.message}}}
function episodes(){const rows=Object.entries(data.episodes).sort((a,b)=>(b[1].processed_at||b[1].updated_at||"").localeCompare(a[1].processed_at||a[1].updated_at||"")).slice(0,300);view.innerHTML='<div class="panel"><div class="table-wrap"><table><thead><tr><th>פרק</th><th>פודקאסט</th><th>Drive</th><th>Yemos</th><th>סטטוס</th></tr></thead><tbody>'+rows.map(([k,e])=>'<tr><td>'+esc(e.title||k)+'</td><td>'+esc(e.podcast_id||"")+'</td><td>'+(e.drive_file_id?badge("uploaded"):"—")+'</td><td>'+badge(e.yemos_status||"—")+'</td><td>'+badge(e.status||"—")+'</td></tr>').join("")+'</tbody></table></div></div>'}
function runs(){view.innerHTML='<div class="panel"><div class="table-wrap"><table><thead><tr><th>#</th><th>אירוע</th><th>מצב</th><th>התחלה</th><th>GitHub</th></tr></thead><tbody>'+data.runs.map(r=>'<tr><td>'+r.number+'</td><td>'+r.event+'</td><td>'+badge(r.status==="completed"?r.conclusion:r.status)+'</td><td>'+date(r.created_at)+'</td><td><a target="_blank" href="'+r.html_url+'">פתח</a></td></tr>').join("")+'</tbody></table></div></div>'}
function errors(){const rows=Object.values(data.episodes).filter(e=>e.status==="error"||e.yemos_status==="error"||e.error||e.yemos_error);view.innerHTML='<div class="panel"><h2>'+rows.length+' שגיאות בפרקים</h2><div class="table-wrap"><table><thead><tr><th>פרק</th><th>פודקאסט</th><th>שגיאה</th></tr></thead><tbody>'+rows.map(e=>'<tr><td>'+esc(e.title||"")+'</td><td>'+esc(e.podcast_id||"")+'</td><td>'+esc(e.error||e.yemos_error||"")+'</td></tr>').join("")+'</tbody></table></div></div>'}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function attr(s){return esc(s)}
async function login(){password=$("#password").value;sessionStorage.setItem("podcastDashboardPassword",password);try{await load();$("#login").classList.add("hidden");$("#app").classList.remove("hidden");render("overview")}catch(e){$("#loginError").textContent=e.message;sessionStorage.removeItem("podcastDashboardPassword")}}
$("#loginBtn").onclick=login;$("#password").onkeydown=e=>{if(e.key==="Enter")login()};$("#logout").onclick=()=>{sessionStorage.clear();location.reload()};$("#refresh").onclick=async()=>{await load();render(current)};document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>render(b.dataset.view));
if(password)login();
